"""create processed_documents table

Revision ID: 0c1f118c07c6
Revises: 
Create Date: 2026-03-20 16:13:19.499594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c1f118c07c6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_name', sa.Text(), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('project', sa.Text(), nullable=True),
    sa.Column('domain', sa.Text(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('docling_document_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata_extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path')
    )
    op.create_index('ix_processed_documents_domain', 'processed_documents', ['domain'], unique=False)
    op.create_index('ix_processed_documents_file_path', 'processed_documents', ['file_path'], unique=True)
    op.create_index('ix_processed_documents_project', 'processed_documents', ['project'], unique=False)
    op.create_index('ix_processed_documents_status', 'processed_documents', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_processed_documents_status', table_name='processed_documents')
    op.drop_index('ix_processed_documents_project', table_name='processed_documents')
    op.drop_index('ix_processed_documents_file_path', table_name='processed_documents')
    op.drop_index('ix_processed_documents_domain', table_name='processed_documents')
    op.drop_table('processed_documents')
    # ### end Alembic commands ###
