"""create schema_extraction_runs table

Revision ID: 658d756882d4
Revises: de0f79cd95b8
Create Date: 2026-03-23 21:02:07.784763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '658d756882d4'
down_revision: Union[str, Sequence[str], None] = 'de0f79cd95b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schema_extraction_runs',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('provider', sa.Text(), nullable=True),
    sa.Column('total_entity_types', sa.Integer(), nullable=True),
    sa.Column('total_relationships', sa.Integer(), nullable=True),
    sa.Column('total_duration_ms', sa.Integer(), nullable=True),
    sa.Column('cqs_used', sa.Integer(), nullable=True),
    sa.Column('seed_reference_used', sa.Boolean(), nullable=True),
    sa.Column('domains_processed', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pass_outputs_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schema_extraction_runs')
    # ### end Alembic commands ###
