"""add merge fields to cq_clusters and competency_questions plus merge_runs table

Revision ID: b597cf975518
Revises: f31c43659078
Create Date: 2026-03-23 11:07:04.592048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b597cf975518'
down_revision: Union[str, Sequence[str], None] = 'f31c43659078'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merge_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('provider', sa.Text(), nullable=True),
    sa.Column('total_cqs_input', sa.Integer(), nullable=True),
    sa.Column('total_clusters', sa.Integer(), nullable=True),
    sa.Column('total_singletons', sa.Integer(), nullable=True),
    sa.Column('total_gap_fills', sa.Integer(), nullable=True),
    sa.Column('mean_cluster_size', sa.Float(), nullable=True),
    sa.Column('mean_intra_similarity', sa.Float(), nullable=True),
    sa.Column('agreement_distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('quality_distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hierarchy_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('gap_report_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tier3_results_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('competency_questions', sa.Column('embedding_cq_type', sa.String(length=20), nullable=True))
    op.add_column('competency_questions', sa.Column('embedding_cq_type_confidence', sa.Float(), nullable=True))
    op.add_column('competency_questions', sa.Column('rule_cq_type', sa.String(length=20), nullable=True))
    op.add_column('competency_questions', sa.Column('type_agreement', sa.Boolean(), nullable=True))
    op.add_column('cq_clusters', sa.Column('cluster_quality_score', sa.Float(), nullable=True))
    op.add_column('cq_clusters', sa.Column('max_membership_probability', sa.Float(), nullable=True))
    op.add_column('cq_clusters', sa.Column('min_pairwise_similarity', sa.Float(), nullable=True))
    op.add_column('cq_clusters', sa.Column('quality', sa.String(length=10), nullable=True))
    op.add_column('cq_clusters', sa.Column('cross_domain', sa.Boolean(), nullable=True))
    op.add_column('cq_clusters', sa.Column('domain_distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('cq_clusters', sa.Column('has_human_anchor', sa.Boolean(), nullable=True))
    op.add_column('cq_clusters', sa.Column('cq_type_distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('cq_clusters', sa.Column('embedding_domain', sa.Text(), nullable=True))
    op.add_column('cq_clusters', sa.Column('embedding_domain_confidence', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'cq_clusters', 'competency_questions', ['canonical_cq_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cq_clusters', type_='foreignkey')
    op.drop_column('cq_clusters', 'embedding_domain_confidence')
    op.drop_column('cq_clusters', 'embedding_domain')
    op.drop_column('cq_clusters', 'cq_type_distribution')
    op.drop_column('cq_clusters', 'has_human_anchor')
    op.drop_column('cq_clusters', 'domain_distribution')
    op.drop_column('cq_clusters', 'cross_domain')
    op.drop_column('cq_clusters', 'quality')
    op.drop_column('cq_clusters', 'min_pairwise_similarity')
    op.drop_column('cq_clusters', 'max_membership_probability')
    op.drop_column('cq_clusters', 'cluster_quality_score')
    op.drop_column('competency_questions', 'type_agreement')
    op.drop_column('competency_questions', 'rule_cq_type')
    op.drop_column('competency_questions', 'embedding_cq_type_confidence')
    op.drop_column('competency_questions', 'embedding_cq_type')
    op.drop_table('merge_runs')
    # ### end Alembic commands ###
