"""create schema_merge_runs table

Revision ID: de0f79cd95b8
Revises: b597cf975518
Create Date: 2026-03-23 18:40:34.532445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de0f79cd95b8'
down_revision: Union[str, Sequence[str], None] = 'b597cf975518'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schema_merge_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('extraction_run_id', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('provider', sa.Text(), nullable=True),
    sa.Column('input_entity_types', sa.Integer(), nullable=True),
    sa.Column('input_relationships', sa.Integer(), nullable=True),
    sa.Column('input_cqs', sa.Integer(), nullable=True),
    sa.Column('seed_types_count', sa.Integer(), nullable=True),
    sa.Column('merged_entity_types', sa.Integer(), nullable=True),
    sa.Column('merged_relationships', sa.Integer(), nullable=True),
    sa.Column('cq_coverage_rate', sa.Float(), nullable=True),
    sa.Column('cross_pass_agreement_rate', sa.Float(), nullable=True),
    sa.Column('provenance_distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('richness_distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('seed_schema_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schema_merge_runs')
    # ### end Alembic commands ###
