"""create competency_questions and cq_clusters tables

Revision ID: f31c43659078
Revises: 0c1f118c07c6
Create Date: 2026-03-22 22:13:56.570480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f31c43659078'
down_revision: Union[str, Sequence[str], None] = '0c1f118c07c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cq_clusters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_cq_id', sa.UUID(), nullable=True),
    sa.Column('domain', sa.Text(), nullable=True),
    sa.Column('agreement_tier', sa.String(length=10), nullable=True),
    sa.Column('source_passes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('member_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['canonical_cq_id'], ['competency_questions.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competency_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_text', sa.Text(), nullable=False),
    sa.Column('raw_user_input', sa.Text(), nullable=True),
    sa.Column('cq_type', sa.String(length=20), nullable=False),
    sa.Column('domain', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('source_pass', sa.String(length=20), nullable=True),
    sa.Column('template_id', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('previous_text', sa.Text(), nullable=True),
    sa.Column('generation_confidence', sa.Float(), nullable=True),
    sa.Column('verification_confidence', sa.Float(), nullable=True),
    sa.Column('verification_status', sa.String(length=30), nullable=True),
    sa.Column('verification_path', sa.Text(), nullable=True),
    sa.Column('verification_gap', sa.Text(), nullable=True),
    sa.Column('linked_document_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cluster_id', sa.UUID(), nullable=True),
    sa.Column('metadata_extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['cq_clusters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cq_cluster_id', 'competency_questions', ['cluster_id'], unique=False)
    op.create_index('ix_cq_domain', 'competency_questions', ['domain'], unique=False)
    op.create_index('ix_cq_priority', 'competency_questions', ['priority'], unique=False)
    op.create_index('ix_cq_source', 'competency_questions', ['source'], unique=False)
    op.create_index('ix_cq_status', 'competency_questions', ['status'], unique=False)
    op.create_index('ix_cq_verification_status', 'competency_questions', ['verification_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cq_verification_status', table_name='competency_questions')
    op.drop_index('ix_cq_status', table_name='competency_questions')
    op.drop_index('ix_cq_source', table_name='competency_questions')
    op.drop_index('ix_cq_priority', table_name='competency_questions')
    op.drop_index('ix_cq_domain', table_name='competency_questions')
    op.drop_index('ix_cq_cluster_id', table_name='competency_questions')
    op.drop_table('competency_questions')
    op.drop_table('cq_clusters')
    # ### end Alembic commands ###
