"""Query/Response audit-trail writer for the retrieval pipeline (D267, Chunk 35b).

Persists ``Query_Event`` and ``Response_Event`` meta-entity vertices and
``retrieved_from`` edges (Query_Event -> retrieved domain entity) to
ArcadeDB. Mirrors the ``Extraction_Event`` / ``produced_by`` pattern in
:mod:`src.extraction.provenance`, but writes only via OpenCypher
(no Postgres mirror — graph is the source of truth for query audit).

CF3 permanent exemption: this file is allowlisted in
``scripts/check-retrieval-unchanged.sh`` (D267 + 35a accumulator).

Public API
----------

* :func:`persist_query_response` — invoked from
  ``src/api/retrieval_routes.py`` after the pipeline returns. The route
  layer generates ``query_event_id`` (server-side UUID4, B1 resolution)
  and threads it through the writer.
* :func:`compare_retrieval_sets` — replay diff between two
  ``query_event_id``\\ s; reads ``retrieved_from`` edges and returns
  ``{added, removed, unchanged}`` grace_id lists.

Design notes
------------

* Writer uses the existing ``ArcadeClient.execute_cypher`` interface
  (language defaulting to ``"opencypher"``) — same primitive used by
  ``entity_ops``. We do NOT import ``graph_writer.write_batch``: query
  events are not extraction batches and have no D106 idempotency contract
  beyond "duplicate query_event_id is a no-op."
* Idempotency is per ``query_event_id``: if a vertex already exists the
  function short-circuits and does not double-create the edges.
* Failures are surfaced as exceptions to the caller; the route handler
  wraps the call in try/except so writer faults never break the query
  path (log-and-continue).
"""

from __future__ import annotations

import json
from datetime import UTC, datetime
from typing import Any
from uuid import uuid4

import structlog

from src.graph.arcade_client import ArcadeClient
from src.graph.cypher_utils import build_property_map, escape_cypher_string

log = structlog.get_logger()


async def _query_event_exists(client: ArcadeClient, query_event_id: str) -> bool:
    """Return True if a Query_Event vertex with this id already exists."""
    escaped = escape_cypher_string(query_event_id)
    query = (
        f"MATCH (q:Query_Event {{query_event_id: '{escaped}'}}) "
        f"RETURN q.grace_id LIMIT 1"
    )
    result = await client.execute_cypher(query)
    rows = result.get("result", [])
    return bool(rows)


def _encode_sensitivity_tags(tags: list[str] | None) -> str | None:
    """Encode a list of sensitivity tag names as a bar-delimited STRING.

    D349 (Chunk 43 CP5) — persisted form is ``"|tag1|tag2|"`` so the
    audit-trail filter route can use exact ``CONTAINS '|tag|'`` matching
    without JSON-substring prefix collisions. Empty / None → ``None``
    (the writer's :func:`build_property_map` skips ``None`` values, so
    vertices with no tags omit the property entirely).

    Tag names containing the bar character are skipped with a warning
    rather than silently corrupted; sensitivity tag taxonomy in
    :mod:`src.permissions.models` already restricts to ASCII identifiers
    in practice.
    """
    if not tags:
        return None
    safe: list[str] = []
    for raw in tags:
        if not isinstance(raw, str):
            continue
        clean = raw.strip()
        if not clean:
            continue
        if "|" in clean:
            log.warning(
                "query_event_writer.sensitivity_tag_skipped",
                reason="tag contains '|' delimiter",
                tag=clean,
            )
            continue
        safe.append(clean)
    if not safe:
        return None
    # Sort + dedupe so persisted form is canonical.
    return "|" + "|".join(sorted(set(safe))) + "|"


async def persist_query_response(
    client: ArcadeClient,
    query_event_id: str,
    query_text: str,
    results: list,
    response_metadata: dict[str, Any],
    sensitivity_tags: list[str] | None = None,
    sensitivity_tags_matrix_id: str | None = None,
    support_session_id: str | None = None,
) -> dict[str, int]:
    """Persist a Query_Event + Response_Event vertex pair and per-result edges.

    Args:
        client: live ArcadeDB HTTP client.
        query_event_id: UUID4 string generated by the route handler
            (B1 resolution: server-side generation).
        query_text: raw query text submitted by the user.
        results: list of objects with at least ``grace_id`` and ``rerank_score``
            attributes (typically :class:`~src.retrieval.retrieval_models.RankedResult`).
        response_metadata: dict carrying optional keys
            ``session_id``, ``retrieval_mode``, ``strategies_fired``
            (list[str]), ``total_candidates`` (int), ``result_count`` (int),
            ``serialization_format`` (str), ``latency_ms_total`` (float).
        sensitivity_tags: optional active-matrix sensitivity tag names
            (D349, Chunk 43 CP5). Persisted on the same Query_Event vertex
            INSERT — never a separate UPDATE per D345. Empty / None means
            "matrix had no tags or none were resolvable"; the property is
            omitted from the vertex entirely.
        sensitivity_tags_matrix_id: optional UUID string of the active
            matrix that supplied ``sensitivity_tags`` (Q3 SOC 2 fidelity).
        support_session_id: optional UUID string of the active support
            session (D377, Chunk 45 CP5). When set, stamped on the
            Query_Event vertex for transcript builder queries.

    Returns:
        ``{"query_events_created", "response_events_created", "edges_created"}``
        — count summary suitable for logging / metrics.

    Idempotency
    -----------
    If a ``Query_Event`` with the given ``query_event_id`` already exists
    the function returns immediately with all counts == 0; no Response_Event
    or retrieved_from edges are written. Replay safety mirrors the
    ``produced_by`` pattern in :mod:`src.extraction.provenance`.
    """
    if await _query_event_exists(client, query_event_id):
        log.info(
            "query_event_writer.idempotent_skip",
            query_event_id=query_event_id,
        )
        return {
            "query_events_created": 0,
            "response_events_created": 0,
            "edges_created": 0,
        }

    now = datetime.now(UTC)
    query_grace_id = str(uuid4())
    response_grace_id = str(uuid4())
    response_event_id = str(uuid4())

    strategies_fired = response_metadata.get("strategies_fired") or []
    if not isinstance(strategies_fired, list):
        strategies_fired = list(strategies_fired)

    query_props: dict[str, Any] = {
        "grace_id": query_grace_id,
        "query_event_id": query_event_id,
        "query_text": query_text,
        "query_timestamp": now,
        "session_id": response_metadata.get("session_id"),
        "retrieval_mode": response_metadata.get("retrieval_mode") or "single_round",
        "strategies_fired": json.dumps(strategies_fired),
        "total_candidates": int(response_metadata.get("total_candidates") or 0),
        # D349 (Chunk 43 CP5) — Sensitivity Gate audit annotation.
        # ``build_property_map`` skips ``None`` so vertices without an
        # active matrix or with a tag-free matrix omit both fields.
        "sensitivity_tags": _encode_sensitivity_tags(sensitivity_tags),
        "sensitivity_tags_matrix_id": (
            sensitivity_tags_matrix_id if sensitivity_tags_matrix_id else None
        ),
        # D377 (Chunk 45 CP5) — support session audit stamp.
        # build_property_map skips None so vertices without a support
        # session omit the property entirely (existing behavior preserved).
        "support_session_id": support_session_id if support_session_id else None,
    }
    query_prop_map = build_property_map(query_props)
    await client.execute_cypher(
        f"CREATE (n:Query_Event {query_prop_map}) RETURN n.grace_id"
    )

    response_props: dict[str, Any] = {
        "grace_id": response_grace_id,
        "response_event_id": response_event_id,
        "query_event_id": query_event_id,
        "result_count": int(response_metadata.get("result_count") or len(results)),
        "serialization_format": response_metadata.get("serialization_format") or "",
        "latency_ms_total": float(response_metadata.get("latency_ms_total") or 0.0),
        "created_at": now,
    }
    response_prop_map = build_property_map(response_props)
    await client.execute_cypher(
        f"CREATE (n:Response_Event {response_prop_map}) RETURN n.grace_id"
    )

    edges_created = 0
    escaped_query_grace_id = escape_cypher_string(query_grace_id)
    escaped_qeid = escape_cypher_string(query_event_id)
    for ordinal, item in enumerate(results, start=1):
        target_grace_id = _result_grace_id(item)
        if not target_grace_id:
            continue
        escaped_target = escape_cypher_string(target_grace_id)
        edge_grace_id = str(uuid4())
        edge_props = {
            "grace_id": edge_grace_id,
            "created_at": now.isoformat(),
            "query_event_id": query_event_id,
            "rank_ordinal": ordinal,
        }
        # Build edge property map manually so created_at stays a string literal
        # rather than a datetime; ArcadeDB accepts ISO 8601 strings.
        edge_props_map = (
            "{"
            f"grace_id: '{escape_cypher_string(edge_grace_id)}', "
            f"created_at: '{escape_cypher_string(now.isoformat())}', "
            f"query_event_id: '{escaped_qeid}', "
            f"rank_ordinal: {ordinal}"
            "}"
        )
        # Edge query: from the just-created Query_Event vertex to the existing entity.
        create_query = (
            f"MATCH (q:Query_Event {{grace_id: '{escaped_query_grace_id}'}}), "
            f"(e {{grace_id: '{escaped_target}'}}) "
            f"CREATE (q)-[:retrieved_from {edge_props_map}]->(e) "
            f"RETURN q.grace_id"
        )
        _ = edge_props  # retained for trace; actual literal is in edge_props_map
        await client.execute_cypher(create_query)
        edges_created += 1

    log.info(
        "query_event_writer.persisted",
        query_event_id=query_event_id,
        query_grace_id=query_grace_id,
        response_grace_id=response_grace_id,
        edges_created=edges_created,
    )

    return {
        "query_events_created": 1,
        "response_events_created": 1,
        "edges_created": edges_created,
    }


def _result_grace_id(item: Any) -> str | None:
    """Best-effort grace_id extraction from a result item.

    Accepts both Pydantic objects (``RankedResult``) and plain dicts so
    the writer is decoupled from the retrieval models package. Returns
    ``None`` when the field is missing — the caller silently skips that
    result for edge creation rather than raising.
    """
    if hasattr(item, "grace_id"):
        return getattr(item, "grace_id") or None
    if isinstance(item, dict):
        return item.get("grace_id") or None
    return None


# --------------------------------------------------------------------------- #
# CP6 — replay diff
# --------------------------------------------------------------------------- #


async def _retrieved_grace_ids_for_query(
    client: ArcadeClient, query_event_id: str
) -> list[str]:
    """Return the list of grace_ids for entities retrieved by a query event.

    Sorted by ``rank_ordinal`` ascending (tied ranks preserve write order).
    """
    escaped = escape_cypher_string(query_event_id)
    query = (
        f"MATCH (q:Query_Event {{query_event_id: '{escaped}'}})"
        f"-[r:retrieved_from]->(e) "
        f"RETURN e.grace_id AS grace_id, r.rank_ordinal AS rank_ordinal "
        f"ORDER BY r.rank_ordinal"
    )
    result = await client.execute_cypher(query)
    rows = result.get("result", []) or []
    grace_ids: list[str] = []
    for row in rows:
        if not isinstance(row, dict):
            continue
        gid = row.get("grace_id")
        if isinstance(gid, str) and gid:
            grace_ids.append(gid)
    return grace_ids


async def compare_retrieval_sets(
    client: ArcadeClient,
    query_event_id_a: str,
    query_event_id_b: str,
) -> dict[str, list[str]]:
    """Compare retrieval sets between two query events.

    Returns ``{"added", "removed", "unchanged"}`` where:

    * ``added``: grace_ids in B but not A.
    * ``removed``: grace_ids in A but not B.
    * ``unchanged``: grace_ids in both.

    Each list is deterministic in order: the diff lists follow the
    rank order of B (added) / A (removed) / A (unchanged).
    """
    a_ids = await _retrieved_grace_ids_for_query(client, query_event_id_a)
    b_ids = await _retrieved_grace_ids_for_query(client, query_event_id_b)
    a_set = set(a_ids)
    b_set = set(b_ids)
    added = [g for g in b_ids if g not in a_set]
    removed = [g for g in a_ids if g not in b_set]
    unchanged = [g for g in a_ids if g in b_set]
    return {"added": added, "removed": removed, "unchanged": unchanged}
